### ISSUE TITLE
An Eclipse Menu screenshot for the memes

### ISSUE THREAD

**Issue by RavenRiftChan** [Rustring/SampleGDModMenu#2]
Here :)

![Screenshot_20240710_002012](https://github.com/Rustring/SampleGDModMenu/assets/174942695/1bae82a1-474e-45a4-b69c-6b8866fca49a)

**Comment by Rustring** [comment]
Bruh

**Comment by Rustring** [comment]
Lol the screenshot is outdated, it looks like Megahack now
