### ISSUE TITLE
Please beg the devs to add this, URGENT 

### ISSUE THREAD

**Issue by RavenRiftChan** [Rustring/SampleGDModMenu#3]
Hack that replaces all SFX with FIRE IN THE HOLE 🔥🔥🕳️🥶🥶

Please I want this, beg them to add this pwease pretty pwease uwu

**Comment by Rustring** [comment]
Bruh has no idea how github works

**Comment by RavenRiftChan** [comment]
> Bruh has no idea how github works

senpaii, pwease understand, i weally want that hack, i want the lobotomy hack, pwease beg the devs to add it, pwease pwease senpaii uwu >.<

**Comment by Rustring** [comment]
My goodness wth is this response

**Comment by Rustring** [comment]
> senpaii, pwease understand, i weally want that hack, i want the lobotomy hack, pwease beg the devs to add it, pwease pwease senpaii uwu >.<

My goodness wth is this response 🤣
And what the heck is "wobotomy" I'll change it for you

**Comment by RavenRiftChan** [comment]
> My goodness wth is this response 🤣 And what the heck is "wobotomy" I'll change it for you

oh hewwo, my wittle cutie pie x3 i weawwy wike tawking in dis wanguwage, pwease, pwease, pwease, wouwd they kindwy consideuw adding it? >.< i wouwd be so gwavefuw uwu x3

**Comment by Rustring** [comment]
I'm done reading this

**Comment by RavenRiftChan** [comment]
hewwo, why did you close my cute issue, pwease beg the devs to add the hack, pwease pwetty pwease, beg them to add it x3

**Comment by Rustring** [comment]
> hewwo, why did you close my cute issue, pwease beg the devs to add the hack, pwease pwetty pwease, beg them to add it x3

Stop being a troll, grow up, touch grass for once
