### ISSUE TITLE
please beg twe devs t-to add fiwe in twe howle ^-^'

### ISSUE THREAD

**Issue by RavenRiftChan** [Rustring/SampleGDModMenu#4]
h-hewwo senpai, pwease ask the devs to add fire in the hole, pwease pwease pwease >.< uwu

**Comment by Rustring** [comment]
Do you even have a **brain**? If you have **any** common sense, I can't just go to them as buddies or mates and say, let's just add this hack, I am **banned** from commenting on their repository, if you had **eyes** ,you could see this is **not** meant to be public and they don't want to deal with anyone who's downloading this, and starts reporting issues. But you UwUChan apparently **don't** have a functioning brain.

**Comment by RavenRiftChan** [comment]
h-hewwo, i-i just wanted to mention that your p-pwofile picture wooks vewy sad, i-i mwean, it w-wooks pwetty depwessed... i-i'm s-sowwy if i-i'm bwinging it up, pwease fowgive m-me x3

**Comment by Rustring** [comment]
I'm not depressed, maybe you just have no idea what **grass** looks like. **Go outside** for once.

**Comment by Rustring** [comment]
I should've realized to not take this seriously, oops
