### ISSUE TITLE
senpai, pwease notith me x3 im so despewate >.< x3 >.< :3 x3 ;3 >///< x3 :3 >///<

### ISSUE THREAD

**Issue by RavenRiftChan** [Rustring/SampleGDModMenu#5]
hewwo, pwease get someone to fix those twansparent wists, it makes evewything buggy wuggy uwu x3

**Comment by Rustring** [comment]
I tried to report but they banned me.

**Comment by Rustring** [comment]
Sorry for the insult I shouldn't have taken you seriously anyways, have a good day.
